[package]
name = "tincture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tincture"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.22.0", features = ["num-bigint"] }
rand = "0.9.0-alpha.2"
num-bigint = "*"